#!/bin/bash
set -e
cd "$(dirname "$0")"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"
SERVER_DIR="${SCRIPT_DIR}/server"
MACOS_DIR="${PARENT_DIR}/macos"
ANDROID_DIR="${PARENT_DIR}/android"

BUILD_VERSION="$(date +%y%m%d%H%M)"
VERSION="0.8.${BUILD_VERSION}"

echo "=========================================="
echo "  IINA Remote Release Build"
echo "  Version: ${VERSION}"
echo "=========================================="
echo ""

echo "=== Step 1: Building Go Server (Release) ==="
cd "$SERVER_DIR"

GO=$(which go 2>/dev/null || command -v go)
[ -z "$GO" ] && echo "Error: Go not found" && exit 1

LDFLAGS="-X main.version=${VERSION}"
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 $GO build -ldflags "${LDFLAGS}" -o iina-remote-server .

echo "Server build complete"
echo "  Binary: ${SERVER_DIR}/iina-remote-server"
echo "  Size: $(ls -lh iina-remote-server | awk '{print $5}')"
echo ""

echo "=== Step 2: Building macOS App (Release) ==="
cd "$MACOS_DIR"

xcodegen generate 2>/dev/null

sed -i '' "s/BUILD_VERSION/${BUILD_VERSION}/g" "${MACOS_DIR}/IINARemote.xcodeproj/project.pbxproj" 2>/dev/null || true
printf '// Generated by BUILD.sh - do not edit\n' > "${MACOS_DIR}/IINARemote/VersionInfo.swift"
printf 'enum VersionInfo {\n' >> "${MACOS_DIR}/IINARemote/VersionInfo.swift"
printf '    static let marketingVersion = "0.8.%s"\n' "${BUILD_VERSION}" >> "${MACOS_DIR}/IINARemote/VersionInfo.swift"
printf '    static let buildVersion = "%s"\n' "${BUILD_VERSION}" >> "${MACOS_DIR}/IINARemote/VersionInfo.swift"
printf '}\n' >> "${MACOS_DIR}/IINARemote/VersionInfo.swift"

xcodebuild -project IINARemote.xcodeproj -scheme IINARemote -configuration Release build CODE_SIGN_IDENTITY="-" CODE_SIGN_STYLE=Manual

MACOS_APP="${MACOS_DIR}/build/Release/IINA Remote.app"
echo ""
echo "macOS build complete"
echo "  App bundle: ${MACOS_APP}"
echo ""

echo "=== Step 3: Building Android App (Release) ==="
cd "$ANDROID_DIR"

./gradlew assembleRelease --no-daemon -q

APK_PATH="${ANDROID_DIR}/app/build/outputs/apk/release/app-release.apk"
if [ ! -f "$APK_PATH" ]; then
    APK_PATH="${ANDROID_DIR}/app/build/outputs/apk/release/app-release-unsigned.apk"
fi

echo ""
echo "Android build complete"
echo "  APK: ${APK_PATH}"
echo "  Size: $(ls -lh "$APK_PATH" 2>/dev/null | awk '{print $5}')"
echo ""

echo "=========================================="
echo "  Release Build Complete"
echo "  Version: ${VERSION}"
echo "=========================================="
echo ""
echo "Build artifacts:"
echo "  Server:   ${SERVER_DIR}/iina-remote-server"
echo "  macOS:    ${MACOS_APP}"
echo "  Android:  ${APK_PATH}"
